# Generated by Django 5.2.14 on 2026-05-18 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="user",
            table="accounts_users",
        ),
    ]
