services:
  - type: web
    name: factflow
    runtime: python
    plan: free
    autoDeploy: true
    buildCommand: ./build.sh
    startCommand: poetry run python manage.py migrate --noinput && poetry run python -m gunicorn config.wsgi:application
    healthCheckPath: /health
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.prod
      - key: SECRET_KEY
        sync: false
      - key: ALLOWED_HOSTS
        sync: false
      - key: CSRF_TRUSTED_ORIGINS
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: SECURE_SSL_REDIRECT
        value: "true"
      - key: SECURE_HSTS_SECONDS
        value: "31536000"
      - key: SECURE_HSTS_INCLUDE_SUBDOMAINS
        value: "true"
      - key: SECURE_HSTS_PRELOAD
        value: "true"
