# Generated by Django 5.2.14 on 2026-05-18 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("partial_success", "Partial success"),
                            ("failed", "Failed"),
                        ],
                        default="success",
                        max_length=32,
                    ),
                ),
                (
                    "error_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("invalid_file_format", "Invalid file format"),
                            ("missing_required_columns", "Missing required columns"),
                            ("invalid_headers", "Invalid headers"),
                            ("invalid_row_data", "Invalid row data"),
                            ("empty_file", "Empty file"),
                            ("no_valid_rows", "No valid rows"),
                            ("unexpected_error", "Unexpected error"),
                        ],
                        max_length=64,
                        null=True,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("total_rows", models.PositiveIntegerField(default=0)),
                ("success_rows", models.PositiveIntegerField(default=0)),
                ("failed_rows", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImportedFact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("advertiser", models.CharField(max_length=255)),
                ("brand", models.CharField(max_length=255)),
                ("start", models.DateField()),
                ("end", models.DateField()),
                ("format", models.CharField(max_length=128)),
                ("platform", models.CharField(max_length=128)),
                ("impr", models.BigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "upload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facts",
                        to="imports.uploadlog",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["start"], name="imports_imp_start_5ec233_idx"),
                    models.Index(
                        fields=["user"], name="imports_imp_user_id_a0fb40_idx"
                    ),
                    models.Index(
                        fields=["upload"], name="imports_imp_upload__7be5e6_idx"
                    ),
                ],
            },
        ),
    ]
