# Generated by Django 5.2.14 on 2026-05-18 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("imports", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="importedfact",
            options={
                "verbose_name": "imported fact",
                "verbose_name_plural": "imported facts",
            },
        ),
        migrations.AlterModelOptions(
            name="uploadlog",
            options={
                "verbose_name": "upload log",
                "verbose_name_plural": "upload logs",
            },
        ),
        migrations.RenameIndex(
            model_name="importedfact",
            new_name="imported_fa_start_3e9e09_idx",
            old_name="imports_imp_start_5ec233_idx",
        ),
        migrations.RenameIndex(
            model_name="importedfact",
            new_name="imported_fa_user_id_e3c885_idx",
            old_name="imports_imp_user_id_a0fb40_idx",
        ),
        migrations.RenameIndex(
            model_name="importedfact",
            new_name="imported_fa_upload__1ea735_idx",
            old_name="imports_imp_upload__7be5e6_idx",
        ),
        migrations.AlterModelTable(
            name="importedfact",
            table="imported_facts",
        ),
        migrations.AlterModelTable(
            name="uploadlog",
            table="import_upload_logs",
        ),
    ]
